# Generated by Django 3.1.5 on 2021-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='whatwedo',
            field=models.CharField(default='nothing', max_length=400),
            preserve_default=False,
        ),
    ]
