# Generated by Django 3.1.5 on 2021-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210120_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mentorResponse',
            field=models.CharField(blank=True, choices=[('want', 'Want'), ('wont', 'Wont'), ('willing', 'Willing')], max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startupResponse',
            field=models.CharField(blank=True, choices=[('want', 'Want'), ('wont', 'Wont'), ('willing', 'Willing')], max_length=200),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('undefined', 'Undefined')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='timeSlot',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('undefined', 'Undefined')], max_length=50),
        ),
    ]
