# Generated by Django 3.1.5 on 2021-01-28 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mentor_mentorpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='endtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
