# Generated by Django 3.1.5 on 2021-01-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='name',
        ),
    ]
