# Generated by Django 3.1.5 on 2021-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210128_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentorPic',
            field=models.URLField(),
        ),
    ]
