# Generated by Django 3.1.5 on 2021-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210130_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='mentorRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startupRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='startupPic',
            field=models.URLField(default='https://image.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'startup'), (2, 'mentor'), (3, 'staff')], default=3, null=True),
        ),
    ]
