# Generated by Django 3.1.5 on 2021-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210201_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='meet',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mentorRank',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startupRank',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
