# Generated by Django 3.1.5 on 2021-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210201_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mentorRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startupRank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
